name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'    # Runs at 02:00 UTC daily
  workflow_dispatch:      # Allow manual run

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Sanity check passed"
